// Copyright (c) 2026 Léonard Adamo (Juste-Leo2) - SPDX-License-Identifier: MIT

package spinalML.memory.litedram

import spinal.core._

/**
 * SpinalHDL BlackBox for the LiteDRAM standalone core generated by
 * `dram/gen/gowin_gen.py` (`dram/out/litedram_core.v`, top module
 * `litedram_core`).
 *
 * Port list must match the generated Verilog exactly (see
 * `dram/configs/tang-primer-20k.yml` for the generating config). The AXI
 * slave port uses the LiteX streaming flavour: single-beat address
 * channels carry `first`/`last`, and write bursts are framed by
 * `w_first`/`w_last` (see `LiteDramAxiBridge`, which adapts standard AXI4
 * to these sidebands). `dest`/`user` params are tied off (unused).
 *
 * Layer 3 physical boundary: board clock/reset/UART on one side, DDR3
 * pads on the other. Everything between (PLL, PHY, controller, JEDEC
 * init) is inside the generated core.
 */
class LiteDramCore(
  axiAddrWidth: Int = 27,
  axiDataWidth: Int = 64,
  axiIdWidth: Int = 4
) extends BlackBox {
  val io = new Bundle {
    val clk27      = in Bool()
    val reset_n    = in Bool()
    val init_done  = out Bool()
    val pll_locked = out Bool()

    // DDR3 pads (Tang Primer 20K footprint, SSTL15/D, see boards pinout).
    val a       = out Bits(14 bits)
    val ba      = out Bits(3 bits)
    val ras_n   = out Bool()
    val cas_n   = out Bool()
    val we_n    = out Bool()
    val cs_n    = out Bool()
    val dm      = out Bits(2 bits)
    val dq      = inout(Analog(Bits(16 bits)))
    val dqs_p   = inout(Analog(Bits(2 bits)))
    val dqs_n   = inout(Analog(Bits(2 bits)))
    val clk_p   = out Bool()
    val clk_n   = out Bool()
    val cke     = out Bool()
    val odt     = out Bool()
    val reset_n_1 = out Bool()

    // AXI slave port, LiteX streaming flavour (inputs from SpinalHDL side).
    val aw_valid         = in Bool()
    val aw_ready         = out Bool()
    val aw_first         = in Bool()
    val aw_last          = in Bool()
    val aw_payload_addr  = in UInt(axiAddrWidth bits)
    val aw_payload_burst = in Bits(2 bits)
    val aw_payload_len   = in UInt(8 bits)
    val aw_payload_size  = in UInt(3 bits)
    val aw_payload_lock  = in Bool()
    val aw_payload_prot  = in Bits(3 bits)
    val aw_payload_cache = in Bits(4 bits)
    val aw_payload_qos   = in Bits(4 bits)
    val aw_payload_region = in Bits(4 bits)
    val aw_param_id      = in UInt(axiIdWidth bits)
    val aw_param_dest    = in Bool()
    val aw_param_user    = in Bool()

    val w_valid       = in Bool()
    val w_ready       = out Bool()
    val w_first       = in Bool()
    val w_last        = in Bool()
    val w_payload_data = in Bits(axiDataWidth bits)
    val w_payload_strb = in Bits(axiDataWidth / 8 bits)
    val w_param_id    = in UInt(axiIdWidth bits)
    val w_param_dest  = in Bool()
    val w_param_user  = in Bool()

    val b_valid       = out Bool()
    val b_ready       = in Bool()
    val b_first       = out Bool()
    val b_last        = out Bool()
    val b_payload_resp = out Bits(2 bits)
    val b_param_id    = out UInt(axiIdWidth bits)
    val b_param_dest  = out Bool()
    val b_param_user  = out Bool()

    val ar_valid         = in Bool()
    val ar_ready         = out Bool()
    val ar_first         = in Bool()
    val ar_last          = in Bool()
    val ar_payload_addr  = in UInt(axiAddrWidth bits)
    val ar_payload_burst = in Bits(2 bits)
    val ar_payload_len   = in UInt(8 bits)
    val ar_payload_size  = in UInt(3 bits)
    val ar_payload_lock  = in Bool()
    val ar_payload_prot  = in Bits(3 bits)
    val ar_payload_cache = in Bits(4 bits)
    val ar_payload_qos   = in Bits(4 bits)
    val ar_payload_region = in Bits(4 bits)
    val ar_param_id      = in UInt(axiIdWidth bits)
    val ar_param_dest    = in Bool()
    val ar_param_user    = in Bool()

    val r_valid       = out Bool()
    val r_ready       = in Bool()
    val r_first       = out Bool()
    val r_last        = out Bool()
    val r_payload_resp = out Bits(2 bits)
    val r_payload_data = out Bits(axiDataWidth bits)
    val r_param_id    = out UInt(axiIdWidth bits)
    val r_param_dest  = out Bool()
    val r_param_user  = out Bool()
  }

  noIoPrefix()
  setDefinitionName("litedram_core")
  // Resolved from the project root when elaborating through Mill/CLI.
  // The file is generated (`dram-gen`), never committed.
  addRTLPath("dram/out/litedram_core.v")
}
