// Copyright (c) 2026 Léonard Adamo (Juste-Leo2) - SPDX-License-Identifier: MIT

package spinalML.nn

import org.scalatest.funsuite.AnyFunSuite
import spinal.core._
import spinal.core.sim._
import spinal.lib.bus.amba4.axi.Axi4Config
import spinal.lib.bus.amba4.axi.sim.{AxiMemorySim, AxiMemorySimConfig, SparseMemory}
import spinalML.dtypes.{FloatML, BF16, I8}
import spinalML.attention.ClassicalAttention

/**
 * Multi-row Linear through the high-level API (features-last convention):
 * an [M, K] input flows through Linear(K -> N) without Flatten and produces
 * [M, N]. Expected values are generated by the Python goldens
 * (tests/python/golden_models/ops.py: linear_hw + relu_hw on BF16).
 *
 * Weight memory layout pinned here by MatmulOp: stream elements are grouped
 * by lanes = inFeatures, so the stored weight matrix is effectively
 * [outFeatures, inFeatures] (torch-style W^T), one row per AXI beat.
 */
class MultiRowLinearTest extends AnyFunSuite {
  val axiConfig = Axi4Config(addressWidth = 32, dataWidth = 64, idWidth = 4)

  def bf16Bits(f: Float): Int = (java.lang.Float.floatToIntBits(f) >>> 16) & 0xFFFF

  def word(elems: Seq[Int]): BigInt =
    elems.zipWithIndex.foldLeft(BigInt(0))((acc, e) => acc | (BigInt(e._1 & 0xFFFF) << (16 * e._2)))

  def writeWords(mem: SparseMemory, base: Int, words: Seq[BigInt]): Unit =
    for ((w, i) <- words.zipWithIndex) mem.writeBigInt(base + i * 8, w, 8)

  def getFloat(p: Data): Float = {
    val f = p.asInstanceOf[FloatML]
    val bits = ((if (f.sign.toBoolean) 1 else 0) << 15) | ((f.exponent.toInt & 0xFF) << 7) | (f.mantissa.toInt & 0x7F)
    java.lang.Float.intBitsToFloat(bits << 16)
  }

  case class MultiRowLinearDut(override val axiConfig: Axi4Config) extends Accelerator(
    dataType = BF16(),
    inputShape = Seq(2, 4),
    modelSpec = Seq(
      Linear(inFeatures = 4, outFeatures = 3),
      ReLU()
    ),
    axiConfig = axiConfig
  )

  test("Sequential multi-row Linear compilation") {
    SpinalConfig().generateVerilog(MultiRowLinearDut(axiConfig))
  }

  test("Multi-row Linear SoC runtime golden (BF16 [2,4] x [4,3] + ReLU)") {
    SimConfig.withVerilator.compile(MultiRowLinearDut(axiConfig)).doSim { dut =>
      dut.clockDomain.forkStimulus(10)

      val memorySim = AxiMemorySim(
        axi = dut.io.axiMaster,
        clockDomain = dut.clockDomain,
        config = AxiMemorySimConfig(maxOutstandingReads = 8)
      )
      memorySim.start()

      // X = [[1.0, 2.0, 3.0, 4.0], [-1.0, 0.5, 0.25, -2.0]]
      val imgBase = 0x1000
      val xWords = Seq(
        Seq(1.0f, 2.0f, 3.0f, 4.0f),
        Seq(-1.0f, 0.5f, 0.25f, -2.0f)
      ).map(row => word(row.map(bf16Bits)))
      writeWords(memorySim.memory, imgBase, xWords)

      // W stored as [outFeatures=3][inFeatures=4]: rows are columns of the
      // logical W = [[1,0,-1],[0.5,2,0],[0,0.5,1],[-0.5,0,2]]
      // b = [0.25, -0.25, 0.0]
      val weightBase = 0x2000
      val wWords = Seq(
        Seq(1.0f, 0.5f, 0.0f, -0.5f),
        Seq(0.0f, 2.0f, 0.5f, 0.0f),
        Seq(-1.0f, 0.0f, 1.0f, 2.0f),
        Seq(0.25f, -0.25f, 0.0f, 0.0f)
      ).map(row => word(row.map(bf16Bits)))
      writeWords(memorySim.memory, weightBase, wWords)

      def writeAxiLite(addr: BigInt, data: BigInt) = {
        dut.io.ctrlBus.aw.valid #= true
        dut.io.ctrlBus.aw.payload.addr #= addr
        dut.io.ctrlBus.w.valid #= true
        dut.io.ctrlBus.w.payload.data #= data
        dut.io.ctrlBus.w.payload.strb #= 0xF
        dut.io.ctrlBus.b.ready #= true

        dut.clockDomain.waitSamplingWhere(dut.io.ctrlBus.aw.ready.toBoolean && dut.io.ctrlBus.w.ready.toBoolean)
        dut.io.ctrlBus.aw.valid #= false
        dut.io.ctrlBus.w.valid #= false
        dut.clockDomain.waitSamplingWhere(dut.io.ctrlBus.b.valid.toBoolean)
        dut.io.ctrlBus.b.ready #= false
        dut.clockDomain.waitSampling()
      }

      dut.io.ctrlBus.aw.valid #= false
      dut.io.ctrlBus.w.valid #= false
      dut.io.ctrlBus.ar.valid #= false
      dut.io.ctrlBus.r.ready #= false
      dut.io.ctrlBus.b.ready #= false
      dut.io.outStream.stream.ready #= true

      dut.clockDomain.waitSampling(5)

      writeAxiLite(0x08, imgBase)
      writeAxiLite(0x0C, weightBase)
      writeAxiLite(0x00, 1)

      val expected = Seq(0.25f, 5.25f, 10.0f, 0.5f, 0.875f, 0.0f)
      var collected = scala.collection.mutable.ArrayBuffer[Float]()
      var timeout = 0
      while (collected.length < expected.length && timeout < 100000) {
        if (dut.io.outStream.stream.valid.toBoolean && dut.io.outStream.stream.ready.toBoolean) {
          collected += getFloat(dut.io.outStream.stream.payload(0))
        }
        dut.clockDomain.waitSampling()
        timeout += 1
      }

      assert(collected.length == expected.length,
        s"Expected ${expected.length} output beats, got ${collected.length}")
      assert(collected.toSeq == expected,
        s"Expected $expected, got $collected")
    }
  }

  case class AttentionFfnDut(numHeads: Int, override val axiConfig: Axi4Config) extends Accelerator(
    dataType = BF16(),
    inputShape = Seq(4, 4),
    modelSpec = Seq(
      ClassicalAttention(
        embedDim = 4,
        numHeads = numHeads,
        customWeightType = Some(I8()),
        weightScales = Seq.fill(4)(0.5)
      ),
      Linear(
        inFeatures = 4,
        outFeatures = 2,
        customWeightType = Some(I8()),
        weightScales = Seq(0.3)
      )
    ),
    axiConfig = axiConfig
  )

  for (heads <- Seq(1, 2)) {
    test(s"Transformer FFN head: ClassicalAttention -> Linear without Flatten (heads=$heads) SoC runtime") {
      SimConfig.withVerilator.compile(AttentionFfnDut(heads, axiConfig)).doSim { dut =>
        dut.clockDomain.forkStimulus(10)

        val memorySim = AxiMemorySim(
          axi = dut.io.axiMaster,
          clockDomain = dut.clockDomain,
          config = AxiMemorySimConfig(maxOutstandingReads = 8)
        )
        memorySim.start()

        val imgBase = 0x1000
        for (i <- 0 until 2) {
          memorySim.memory.writeBigInt(imgBase + i * 8, BigInt("3C003C003C003C00", 16), 8)
        }

        // Attention Wq|Wk|Wv|Wo [16, 4] I8 = 64 B, Linear W [2, 4] I8 = 8 B,
        // Linear bias [1, 2] BF16 = 4 B
        val weightBase = 0x2000
        for (i <- 0 until 9) {
          memorySim.memory.writeBigInt(weightBase + i * 8, BigInt("0101010101010101", 16), 8)
        }
        memorySim.memory.writeBigInt(weightBase + 72, word(Seq(bf16Bits(0.5f), bf16Bits(-0.25f), 0, 0)), 8)

        def writeAxiLite(addr: BigInt, data: BigInt) = {
          dut.io.ctrlBus.aw.valid #= true
          dut.io.ctrlBus.aw.payload.addr #= addr
          dut.io.ctrlBus.w.valid #= true
          dut.io.ctrlBus.w.payload.data #= data
          dut.io.ctrlBus.w.payload.strb #= 0xF
          dut.io.ctrlBus.b.ready #= true

          dut.clockDomain.waitSamplingWhere(dut.io.ctrlBus.aw.ready.toBoolean && dut.io.ctrlBus.w.ready.toBoolean)
          dut.io.ctrlBus.aw.valid #= false
          dut.io.ctrlBus.w.valid #= false
          dut.clockDomain.waitSamplingWhere(dut.io.ctrlBus.b.valid.toBoolean)
          dut.io.ctrlBus.b.ready #= false
          dut.clockDomain.waitSampling()
        }

        dut.io.ctrlBus.aw.valid #= false
        dut.io.ctrlBus.w.valid #= false
        dut.io.ctrlBus.ar.valid #= false
        dut.io.ctrlBus.r.ready #= false
        dut.io.ctrlBus.b.ready #= false
        dut.io.outStream.stream.ready #= true

        dut.clockDomain.waitSampling(5)

        writeAxiLite(0x08, imgBase)
        writeAxiLite(0x0C, weightBase)
        writeAxiLite(0x00, 1)

        val expectedBeats = 4 * 2
        var beatCount = 0
        var timeout = 0
        while (beatCount < expectedBeats && timeout < 100000) {
          if (dut.io.outStream.stream.valid.toBoolean && dut.io.outStream.stream.ready.toBoolean) {
            beatCount += 1
          }
          dut.clockDomain.waitSampling()
          timeout += 1
        }

        assert(timeout < 100000, s"Timeout: only $beatCount/$expectedBeats output beats")
        assert(beatCount == expectedBeats, s"Expected $expectedBeats output beats, got $beatCount")
      }
    }
  }
}
