name: test workflow

on:
  push:
    branches: [ "main" ] 
  workflow_dispatch: 

jobs:
  build:
    runs-on: [self-hosted, arm64, radxa]
    steps:
      - uses: actions/checkout@v4
      - name: Test compilation
        run: echo "Compilation successful !"